# Generated by Django 2.2.6 on 2019-12-06 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FreeNet', '0002_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hesh',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='masege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hesh', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_fazer', models.IntegerField(default=0)),
                ('fazer', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
